import Head from "next/head";
import Image from "next/image";
import { Noto_Sans } from "next/font/google";
import Htag from "@/components/Htag/Htag";
import Button from "@/components/Button/Button";
import Ptag from "@/components/Ptag/Ptag";
// import { JsxElement } from 'typescript'

const notosans = Noto_Sans({ weight: "300", subsets: ["latin"] });

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={notosans.className}>
        <Htag tag="h1">Мій заголовок</Htag>
        <Htag tag="h3">Мій заголовок</Htag>
        <Htag tag="h2">Мій заголовок</Htag>
        <Button appearance="primary" arrow="down">
          Go
        </Button>
        <Button appearance="ghost" arrow="right">
          Stop
        </Button>
        <Ptag size="s">
          У нашому житті є багато речей, які можуть привести нас у пастку, і
          яких ми не можемо уникнути, але Ісус прийшов на цю землю, щоб
          звільнити нас від усього, навіть від смерті! Коли Ісус воскрес із
          мертвих, Він переміг усе погане.
        </Ptag>
        <Ptag size="l">
          У нашому житті є багато речей, які можуть привести нас у пастку, і
          яких ми не можемо уникнути, але Ісус прийшов на цю землю, щоб
          звільнити нас від усього, навіть від смерті! Коли Ісус воскрес із
          мертвих, Він переміг усе погане.
        </Ptag>
        <Ptag>
          У нашому житті є багато речей, які можуть привести нас у пастку, і
          яких ми не можемо уникнути, але Ісус прийшов на цю землю, щоб
          звільнити нас від усього, навіть від смерті! Коли Ісус воскрес із
          мертвих, Він переміг усе погане.
        </Ptag>
      </div>
    </>
  );
}
